### ISSUE TITLE
Problem loading the german model

### ISSUE THREAD

**Issue by talegari** [statsmaths/cleanNLP#2] opened 2017-04-18 12:50 UTC
Dear Taylor Arnold,

Thanks for the package.

> **Problem**: I am able to load the english model with `cleanNLP::init_coreNLP("en")`. I am unable to load the german model with `cleanNLP::init_coreNLP("de")`.

This gives the error message:
```
Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", prop) : 
  edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from edu/stanford/nlp/models/ner/german.hgc_175m_600.crf.ser.gz
```

Details:
- Installed english and geman models using `cleanNLP::download_core_nlp` function. The directory `.../cleanNLP/extdata/stanford-corenlp-full-2016-10-31` contains both `stanford-english-corenlp-2016-10-31-models.jar` and `stanford-german-corenlp-2016-10-31-models.jar` files.
- Here are the contents of `.../cleanNLP/extdata/StanfordCoreNLP-german.Properties`:
```
annotators = tokenize, ssplit, pos, ner, parse
tokenize.language = de
pos.model = edu/stanford/nlp/models/pos-tagger/german/german-hgc.tagger
ner.model = edu/stanford/nlp/models/ner/german.hgc_175m_600.crf.ser.gz
ner.applyNumericClassifiers = false
ner.useSUTime = false
parse.model = edu/stanford/nlp/models/lexparser/germanFactored.ser.gz
```
- session info:
```
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_IN.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_IN.UTF-8           LC_COLLATE=en_IN.UTF-8       
 [5] LC_MONETARY=en_IN.UTF-8       LC_MESSAGES=en_IN.UTF-8      
 [7] LC_PAPER=en_IN.UTF-8          LC_NAME=en_IN.UTF-8          
 [9] LC_ADDRESS=en_IN.UTF-8        LC_TELEPHONE=en_IN.UTF-8     
[11] LC_MEASUREMENT=en_IN.UTF-8    LC_IDENTIFICATION=en_IN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] readr_1.0.0    magrittr_1.5   R6_2.2.0       assertthat_0.1 DBI_0.5-1     
 [6] tools_3.3.3    dplyr_0.5.0    tibble_1.2     Rcpp_0.12.10   rJava_0.9-8   
[11] cleanNLP_1.5.2
```

Edit:

Observed that german properties file  expects the model to have `ner.model = edu/stanford/nlp/models/ner/german.hgc_175m_600.crf.ser.gz` but the jar file actually contains `edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz`. This is confimed with [coreNLP](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/StanfordCoreNLP-german.properties) repo too.

I tried editing my local properties file by adding `.conll`. But, this did not have any effect and the same error message appears.

**Comment by taylor-arnold** [comment] 2017-04-22 14:01
@talegari Thanks for the info. I just uploaded a patch for this, try installing now from GitHub:
```{r}
devtools::install_github("statsmaths/coreNLP")
```
The name of the German NER file was changed in the recent update and I had not fixed in the package.

**Comment by talegari** [comment] 2017-04-24 05:05
@statsmaths Thanks for the patch. It works as expected.

**Comment by fkrauer** [comment] 2019-04-10 09:38
Hi

I have the same problem: 

`Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", prop) : 
  edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz`

I have downloaded the corenNLP java backend through the Stanford website, because the download through `download_core_nlp()` takes too long. The german jar file is in the same folder. I have specified the java library location with

`cnlp_init_corenlp(language = "de",
                  anno_level = 2L, 
                  lib_location = path_to_library`

Could it be that the German NER file was changed again? Could you look into this? 

When I try to initiate the english model, I get a warning message:

`Warning message:
In init_corenlp_backend() :
  English model file has not been downloaded to lib_location.Proceed with caution.`

Even though the files are in the directory. Can't figure out what the problem is. 

Fabienne

session Info

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252   
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cleanNLP_2.3.0

loaded via a namespace (and not attached):
[1] tools_3.3.3

**Comment by taylor-arnold** [comment] 2019-04-11 20:44
It looks like the name for the German NER model was changed in the most recent version. If you reinstall from GH:

```{r}
devtools::install_github("statsmaths/cleanNLP")
```

Then hopefully this will work (it shows what ran on my machine; you'll need to chagne the lib_location path):

```{r}
library(cleanNLP)

lib_location <- "/users/taylor/local/core_nlp_files/stanford-corenlp-full-2018-10-05/"
cnlp_init_corenlp(language = "de", anno_level = 2L, lib_location = lib_location)
x <- cnlp_annotate("Übermorgen fährt Lisa ins Freibad")
cnlp_get_token(x)
```
```
    id sid tid       word      lemma upos     pos cid
2 doc1   1   1 Übermorgen übermorgen NOUN      NN   0
3 doc1   1   2      fährt      fährt VERB   VVFIN  11
4 doc1   1   3       Lisa       lisa NOUN      NE  17
5 doc1   1   4        ins        ins  ADP APPRART  22
6 doc1   1   5    Freibad    freibad NOUN      NN  26
```
```{r}
cnlp_get_entity(x)
```
```
    id sid tid tid_end entity_type entity entity_normalized
1 doc1   0   3       3      PERSON   Lisa                NA
```

Hopefully that solves the problem!

**Comment by taylor-arnold** [comment] 2019-04-11 20:45
And as an aside, I'm hoping to transfer over to the CoreNLP Python implementation soon (the Java backend is slow, buggy, and poorly documented).

**Comment by fkrauer** [comment] 2019-05-03 08:55
Loading the german model works now with the update. Thanks!

**Closed as completed** 2019-05-06 19:52 UTC

**Comment by JuKo007** [comment] 2019-08-16 17:13
I installed cleanNLP from Github today and for me the english and french models are working without issue, however, if I try to initilaize the german model, I get this error: 

```
cnlp_init_corenlp(language = "de")
Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", prop) : 
  edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz
```

**Comment by raoulmes** [comment] 2020-02-12 11:51
Dear Dr. Arnold,
I am running into the same problems as described above using cleanNLP 2.3.0. 
Unfortunately, I am limited to R Version 3.4.4. and do not have access to Python so upgrading to 3.0 is not an option, I guess. 

I downloaded the CoreNLP 3.9.2 files from "stanfordnlp.github.io" and also added the German file: "stanford-german-corenlp-2018-10-05-models.jar" to the folder.

The English Model works with your line from above: 
cnlp_init_corenlp(language = "en", anno_level = 2L, lib_location = lib_location)

For the German model I get the known: 
 Error message: Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", prop) : 
  edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz

Do you have some advice on how to fix this without having to reinstall (and automatically update my cleanNLP version)?

**Comment by taylor-arnold** [comment] 2020-02-12 18:21
Sorry, I don't have access to R 3.4.4 (that's fairly old) and generally am not supporting cleanNLP versions below 3.0.0. The CoreNLP Java interface is not very well documented, particularly the non-English model. I suggest finding a way to upgrade your version of R, or using the udpipe backend.
