### ISSUE TITLE
cnlp_pca() issue: "object 'tfidf' not found"

### ISSUE THREAD

**Issue by cainesap** [statsmaths/cleanNLP#30] opened 2018-03-16 19:34 UTC
Hello,

Firstly, this is a great resource, thank you!

Second, I'm having trouble replicating the PCA analysis from the vignette https://cran.r-project.org/web/packages/cleanNLP/vignettes/case_study.html

The example is as follows:
```
pca <- cnlp_get_token(sotu) %>%
  filter(pos %in% c("NN", "NNS")) %>%
  cnlp_get_tfidf(min_df = 0.05, max_df = 0.95, type = "tfidf", tf_weight = "dnorm") %$%
  cnlp__pca(tfidf, cnlp_get_document(sotu))
```

If I try to run this, (minor error is the double underscore in cnlp__pca()) -- I get the following error message:
```
Error in stats::prcomp(x, center = center, scale. = scale) : 
  object 'tfidf' not found
```

I'm not sure how to fix this: please could you help?
Andrew

**Comment by taylor-arnold** [comment] 2018-03-16 21:29
Great question (and catch on the typo). I just pushed the fix in 4950dbc3c414f7a7b5f0ac6afc171fb64eea9ead. Basically, you just need to do this now because the results of `cnlp_get_tfidif` now returns just a sparse matrix with row and column names:

```{r}
pca <- cnlp_get_token(sotu) %>%
  filter(pos %in% c("NN", "NNS")) %>%
  cnlp_get_tfidf(min_df = 0.05, max_df = 0.95, type = "tfidf", tf_weight = "dnorm") %>%
  cnlp_pca(cnlp_get_document(sotu))
```

And it should work as expected. Please let me know if you still run into any trouble.

**Comment by cainesap** [comment] 2018-03-17 16:15
Thank you for the quick response!
So.. that error goes away but now I get --
`Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric`
-- which made me wonder if one of my nouns is a number, but I checked this and no.
However, I've taken the tfidf object and passed it to plain prcomp(), so this has still been super useful, thanks! Don't worry though, I expect it's a problem with my dataset..
One other question: is it possible to share your plot code for the PCA? It's very good looking!

**Comment by taylor-arnold** [comment] 2018-03-23 14:42
Sure, here is the code that you should be able to adapt to your data:

```
ggplot(pca, aes(PC1, PC2)) +
  geom_point(aes(color = cut(year, 10, dig.lab = 4)), alpha = 0.35, size = 4) +
  geom_text_repel(data = filter(pca, !duplicated(president)),
                  aes(label = president), color = grey(0.4), cex = 3) +
  labs(color = "Year") +
  scale_color_viridis(discrete=TRUE, end = 0.9, option = "C") +
  theme(axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_blank(),
        axis.text.y = element_blank())
```

**Closed as completed** 2018-03-23 14:43 UTC

**Comment by hemiits** [comment] 2018-08-08 09:09
Hi Professor, I tried following your vignette for analysis on the State of the Union address. However, I am unable to reproduce your outputs given the hardcoded input files such as sotu.Rds (Rmd file). Even if I try using the sotu dataset from the sotu package, I get errors about the missing "year".                                                                            cnlp_get_token(sotu) %>%
     group_by(id) %>%
     summarize(n = n()) %>%
     left_join(cnlp_get_document(sotu)) %>%
     ggplot(aes(year, n)) +
     geom_line(color = grey(0.8)) +
     geom_point(aes(color = sotu_type)) +
     geom_smooth()
Joining, by = "id"
Error in FUN(X[[i]], ...) : object 'year' not found

Can you please help. Also, is there code to reproduce the very insightful plot of posterior probabilities over time with labels. 
![image](https://user-images.githubusercontent.com/42203655/43827921-addda8a0-9b2d-11e8-8970-b4ec277189c7.png)

I am also unable to replicate the PCA plot above. The error is:
Error in filter_impl(.data, quo) : 
  Evaluation error: object 'president' not found.

Thank you, appreciate your help.
